User.create!([
  {email: "maxwelle.1122@gmail.com", encrypted_password: "$2a$10$3nsX/rVd32npLMc1IJgGnua5j2shu5F2vkCYlAbBli4GLC5JZ.jee", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: "2014-12-04 18:35:24", sign_in_count: 3, current_sign_in_at: "2014-12-04 22:41:53", last_sign_in_at: "2014-12-04 18:35:24", current_sign_in_ip: "50.52.39.170", last_sign_in_ip: "50.52.39.170"},
  {email: "iqover9000@gmail.com", encrypted_password: "$2a$10$hclmCE1FyXOfIiUaFU1DCe2C4U5BU/QtcjyQG.wipfZ8o2T3dx3XO", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2014-12-11 18:38:52", last_sign_in_at: "2014-12-04 18:01:25", current_sign_in_ip: "96.5.162.3", last_sign_in_ip: "96.5.162.3"},
  {email: "andy.john.jakubek@gmail.com", encrypted_password: "$2a$10$mC9RTx0KwepcQh4170FxNumlh0Ggjjm4wkPO/nlQXj9PRsAdwHKQy", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 6, current_sign_in_at: "2014-12-12 01:22:23", last_sign_in_at: "2014-12-11 00:49:26", current_sign_in_ip: "98.145.166.22", last_sign_in_ip: "98.145.166.22"},
  {email: "zackh1998@gmail.com", encrypted_password: "$2a$10$ICY/3u.X07bWoz7U04mFgu6E1QwYyoZ6bGOm6jDxt64uRdqosFF0q", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 15, current_sign_in_at: "2014-12-13 21:04:34", last_sign_in_at: "2014-12-13 20:57:12", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1"}
])
About.create!([
  {image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, description: nil, name: "Parker Piedmont", email: nil, phone: nil}
])
Answer.create!([
  {text: "Temperate Weather", score: 50, color: "green", question_id: 1, label: "temperate"},
  {text: "Cold Weather", score: 0, color: "blue", question_id: 1, label: "cold"},
  {text: "Normal", score: 50, color: "green", question_id: 2, label: "normal"},
  {text: "Relaxing", score: 0, color: "blue", question_id: 2, label: "relaxing"},
  {text: "Yes", score: 100, color: "red", question_id: 3, label: "yes"},
  {text: "Unsure", score: 50, color: "green", question_id: 3, label: "no"},
  {text: "No", score: 0, color: "blue", question_id: 3, label: "unsure"},
  {text: "Yes", score: 100, color: "red", question_id: 4, label: "yes"},
  {text: "Unsure", score: 50, color: "green", question_id: 4, label: "no"},
  {text: "No", score: 0, color: "blue", question_id: 4, label: "unsure"},
  {text: "Yes", score: 100, color: "red", question_id: 5, label: "yes"},
  {text: "Unsure", score: 50, color: "green", question_id: 5, label: "no"},
  {text: "No", score: 0, color: "blue", question_id: 5, label: "unsure"},
  {text: "Hot Weather", score: 100, color: "red", question_id: 1, label: "hot"},
  {text: "Exciting", score: 100, color: "red", question_id: 2, label: "exciting"}
])
AnswerValue.create!([
  {score: 100, gen_package_id: 1, question_id: 3},
  {score: 15, gen_package_id: 1, question_id: 4},
  {score: 80, gen_package_id: 1, question_id: 5},
  {score: 20, gen_package_id: 2, question_id: 1},
  {score: 40, gen_package_id: 2, question_id: 2},
  {score: 70, gen_package_id: 2, question_id: 3},
  {score: 90, gen_package_id: 2, question_id: 4},
  {score: 65, gen_package_id: 2, question_id: 5},
  {score: 30, gen_package_id: 3, question_id: 1},
  {score: 50, gen_package_id: 3, question_id: 2},
  {score: 60, gen_package_id: 3, question_id: 3},
  {score: 0, gen_package_id: 3, question_id: 4},
  {score: 60, gen_package_id: 3, question_id: 5},
  {score: 20, gen_package_id: 4, question_id: 1},
  {score: 80, gen_package_id: 4, question_id: 2},
  {score: 80, gen_package_id: 4, question_id: 3},
  {score: 0, gen_package_id: 4, question_id: 4},
  {score: 80, gen_package_id: 4, question_id: 5},
  {score: 95, gen_package_id: 5, question_id: 1},
  {score: 90, gen_package_id: 5, question_id: 2},
  {score: 88, gen_package_id: 5, question_id: 3},
  {score: 95, gen_package_id: 5, question_id: 4},
  {score: 75, gen_package_id: 5, question_id: 5},
  {score: 60, gen_package_id: 6, question_id: 1},
  {score: 40, gen_package_id: 6, question_id: 2},
  {score: 50, gen_package_id: 6, question_id: 3},
  {score: 0, gen_package_id: 6, question_id: 4},
  {score: 90, gen_package_id: 6, question_id: 5},
  {score: 100, gen_package_id: 1, question_id: 1},
  {score: 40, gen_package_id: 1, question_id: 2}
])
GenAttraction.create!([
  {name: "Trafalgar Square", description: "Trafalgar Square is a public space and tourist attraction in central London, built around the area formerly known as Charing Cross.", pricing: "10 bucks", location: "Westminster, London WC2N 5DN, United Kingdom", link: "330x210.gif", gen_package_id: 2, image_description: nil, phone: "+44 20 7983 4750", website: "http://www.visitlondon.com/things-to-do/place/283774-trafalgar-square", hours: "ALL DAY", rating: "4.4", iframe_id: "trafalgar", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "The National Gallery", description: "The National Gallery is an art museum in Trafalgar Square in London. Founded in 1824, it houses a collection of over 2,300 paintings dating from the mid-13th century to 1900.", pricing: "10 bucks", location: "Trafalgar Square, London WC2N 5DN, United Kingdom", link: "330x210.gif", gen_package_id: 2, image_description: nil, phone: nil, website: nil, hours: nil, rating: "4.5", iframe_id: "gallery", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Times Square", description: "Times Square is a major commercial intersection and a neighborhood in Midtown Manhattan, New York City, at the junction of Broadway and Seventh Avenue and stretching from West 42nd to West 47th Streets.", pricing: "10 bucks", location: "Manhattan, NY 10036", link: "330x210.gif", gen_package_id: 3, image_description: nil, phone: "N/A", website: "http://www.timessquarenyc.org/index.aspx", hours: "24/7", rating: "5", iframe_id: "times_sq", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Diamond Head State Monument", description: "Diamond Head is the name of a volcanic tuff cone on the Hawaiian island of Oʻahu and known to Hawaiians as Lēʻahi, most likely from lae 'browridge, promontory' plus ʻahi 'tuna' because the shape of the ridgeline resembles the shape of a tuna's dorsal fin.", pricing: "10 bucks", location: "Honolulu, HI 96815", link: "330x210.gif", gen_package_id: 1, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "diamond", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Hawaii Volcanoes National Park", description: "Hawaiʻi Volcanoes National Park, established in 1916, is a United States National Park located in the U.S. State of Hawaiʻi on the island of Hawaiʻi. It encompasses two active volcanoes: Kīlauea, one of the world's most active volcanoes, and Mauna Loa, the world's most massive subaerial volcano.", pricing: "10 bucks", location: "Hawaii Volcanoes National Park, HI 96718", link: "330x210.gif", gen_package_id: 1, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "volcanoes", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Sea Life Park Hawaii", description: "Sea Life Park Hawaii is a marine mammal park, bird sanctuary and aquarium near Makapuʻu Point, north of Hanauma Bay on the island of Oahu in Hawaii,United States.", pricing: "10 bucks", location: "41-202 Kalanianaole Hwy, Waimanalo, HI 96795", link: "330x210.gif", gen_package_id: 1, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "sea_life", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Hanauma Bay", description: "Hanauma is a marine embayment formed within a tuff ring and located along the southeast coast of the Island of Oʻahu (just east of Honolulu) in the Hawaiian Islands.", pricing: "10 bucks", location: "100 Hanauma Bay Rd, Honolulu, HI 96825", link: "330x210.gif", gen_package_id: 1, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "hanauma", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Iolani Palace", description: "ʻIolani Palace, in the capitol district of downtown Honolulu in the U.S. state of Hawaiʻi, is the only royal palace now a part of the United States. It was used as an official residence of the reigning Hawaiian sovereign and is now a National Historic Landmark listed on the National Register of Historic Places.", pricing: "10 bucks", location: "364 S King St, Honolulu, HI 96813", link: "330x210.gif", gen_package_id: 1, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "iolani", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Waipio Valley", description: "Waipiʻo Valley is a valley located in the Hamakua District of the Big Island of Hawaiʻi. \"Waipiʻo\" means \"curved water\" in the Hawaiian language.", pricing: "10 bucks", location: "48-5416 Government Main Rd, Honokaa, HI 96727", link: "330x210.gif", gen_package_id: 1, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "waipio", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Maui Ocean Center", description: "Maui Ocean Center, the Hawaiian Aquarium, is a great activity during any vacation to Maui, whether a family vacation, a romantic honeymoon, a relaxing retreat or an adventurous tour.", pricing: "10 bucks", location: "192 Maalaea Rd, Wailuku, HI 96793", link: "330x210.gif", gen_package_id: 1, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "moc", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Madison Square Garden", description: "Madison Square Garden is a multi-purpose indoor arena in Midtown Manhattan in New York City. Located between Seventh and Eighth Avenues from 31st to 33rd Streets, it is situated atop Pennsylvania Station.", pricing: "10 bucks", location: "4 Pennsylvania Plaza, New York, NY 10001", link: "330x210.gif", gen_package_id: 3, image_description: nil, phone: "(212) 465-6741", website: "http://www.thegarden.com/", hours: "N/A", rating: "5", iframe_id: "madison_sq", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Yankee Stadium", description: "Yankee Stadium is a stadium located in the South Bronx in New York City. It is the home ballpark for the New York Yankees of Major League Baseball, and will also be the home of New York City FC of Major League Soccer.", pricing: "10 bucks", location: "1 E 161st St, Bronx, NY 10451", link: "330x210.gif", gen_package_id: 3, image_description: nil, phone: "(718) 293-4300", website: "http://newyork.yankees.mlb.com/nyy/ballpark/", hours: "N/A", rating: "5", iframe_id: "yankee", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Empire State Building", description: "The Empire State Building is a 103-story skyscraper located in Midtown Manhattan, New York City, at the intersection of Fifth Avenue and West 34th Street. It has a roof height of 1,250 feet, and with its antenna spire included, it stands a total of 1,454 feet high.", pricing: "10 bucks", location: "350 5th Ave, New York, NY 10118", link: "330x210.gif", gen_package_id: 3, image_description: nil, phone: "(212) 736-3100", website: "http://www.esbnyc.com/", hours: "Mon - Sun\t8:00 AM to 2:00 AM", rating: "5", iframe_id: "empire", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "National Mall", description: "The National Mall is a national park in downtown Washington, D.C., the capital of the United States. The National Park Service administers the National Mall, which is part of its National Mall and Memorial Parks unit.", pricing: "10 bucks", location: "Washington, DC", link: "330x210.gif", gen_package_id: 6, image_description: nil, phone: "(202) 426-6841", website: "http://www.nps.gov/nama/index.htm", hours: "N/A", rating: "4.5", iframe_id: "ntl_mall", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Experience Music Project", description: "EMP Museum is a nonprofit museum, dedicated to contemporary popular culture. EMP Museum was founded by Microsoft co-founder Paul Allen in 2000.", pricing: "$$", location: "325 5th Ave N, Seattle, WA 98109", link: "330x210.gif", gen_package_id: 4, image_description: nil, phone: "+1 206 770 2700", website: "empmuseum.org", hours: "10:00 AM -- 5:00 PM", rating: "4.2", iframe_id: "emp", button_id: nil, website_url: "http://www.empmuseum.org/", iframe_url: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2689.2391683091296!2d-122.34812400000001!3d47.621482!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x54901546f87aca63%3A0xd1e929cd1149d812!2sEMP+Museum!5e0!3m2!1sen!2sus!4v1417489798101", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: "hawaii.jpg", image_thumb_content_type: "image/jpeg", image_thumb_file_size: 243361, image_thumb_updated_at: "2014-12-12 04:32:42", short_url: nil},
  {name: "", description: "", pricing: "", location: "", link: "", gen_package_id: nil, image_description: "", phone: "", website: "", hours: "", rating: "", iframe_id: "", button_id: "", website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Churchill War Rooms", description: "The Churchill War Rooms is a museum in London and one of the five branches of the Imperial War Museum. The museum comprises the Cabinet War Rooms, a historic underground complex that housed a British government command centre throughout the Second World War, and the Churchill Museum, a biographical museum exploring the life of British statesman Winston Churchill.", pricing: "10 bucks", location: "Clive Steps, King Charles Street, London SW1A 2AQ, United Kingdom", link: "330x210.gif", gen_package_id: 2, image_description: nil, phone: "+44 20 7930 6961", website: nil, hours: nil, rating: "4.2", iframe_id: "churchill", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Central Parka", description: "Central Park is an urban park in the central part of the borough of Manhattan, New York City . It was initially opened in 1857, on 778 acres of city-owned land.", pricing: "10 bucks", location: "New York, NY", link: "330x210.gif", gen_package_id: 3, image_description: nil, phone: "(212) 310-6600", website: "http://www.centralparknyc.org/", hours: "Monday-Sunday 6:00PM-1:00AM", rating: "5", iframe_id: "cen_pk", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: "asdfasdf"},
  {name: "Buckingham Palace", description: "Buckingham Palace is the London residence and principal workplace of the monarchy of the United Kingdom. Located in the City of Westminster, the palace is often at the centre of state occasions and royal hospitality.", pricing: "10 bucks", location: "London SW1A 1AA, United Kingdom", link: "330x210.gif", gen_package_id: 2, image_description: nil, phone: nil, website: "http://www.royalcollection.org.uk/", hours: nil, rating: "4.3", iframe_id: "buckingham", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: "royalcollection.org.uk"},
  {name: "Tower of London", description: "The Tower of London, also known as “Her Majesty’s Royal Palace and Fortress”, a royal palace made up of a complex of several buildings, was built as a place to protect and control the city of London.", pricing: "10 bucks", location: "London EC3N 4AB, United Kingdom", link: "330x210.gif", gen_package_id: 2, image_description: nil, phone: nil, website: nil, hours: "9:00 am - 5:30 pm", rating: "4.4", iframe_id: "london_tower", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "London Eye", description: "The London Eye is a giant Ferris wheel on the South Bank of the River Thames in London. Also known as the Millennium Wheel, its official name was originally the British Airways London Eye, then the Merlin Entertainments London Eye, between January 2011 and August 2014,  the EDF Energy London Eye and is now called the London Eye.", pricing: "10 bucks", location: "London SE1 7PB, United Kingdom", link: "330x210.gif", gen_package_id: 2, image_description: nil, phone: nil, website: nil, hours: "10:00 am - 8:30 pm", rating: "4.4", iframe_id: "london_eye", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Sydney Opera House", description: "The Sydney Opera House is a multi-venue performing arts centre in Sydney, New South Wales, Australia. Situated on Bennelong Point in Sydney Harbour, close to the Sydney Harbour Bridge, the facility is adjacent to the Sydney central business district and the Royal Botanic Gardens, between Sydney and Farm Coves", pricing: "10 bucks", location: "Bennelong Point, Sydney NSW 2000, Australia", link: "330x210.gif", gen_package_id: 5, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "opera", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Bondi Beach", description: "Bondi Beach or Bondi Bay is a popular beach and the name of the surrounding suburb in Sydney, New South Wales, Australia. Bondi Beach is located 7 km (4 mi) east of the Sydney central business district, in the local government area of Waverley Council, in the Eastern Suburbs. Bondi, North Bondi and Bondi Junction are neighbouring suburbs.", pricing: "10 bucks", location: "NSW 2026, Australia", link: "330x210.gif", gen_package_id: 5, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "bondi", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Manly Sea Life Sanctuary", description: "Manly Sea Life Sanctuary is a public aquarium located in Manly, Australia. Manly SEA LIFE Sanctuary features sharks, giant stingrays, sea turtles, Little Penguins and other marine life.", pricing: "10 bucks", location: "W Esplanade, Manly NSW 2095, Australia", link: "330x210.gif", gen_package_id: 5, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "manly", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Sydney Harbour Bridge", description: "The Sydney Harbour Bridge is a steel through arch bridge across Sydney Harbour that carries rail, vehicular, bicycle and pedestrian traffic between the Sydney central business district (CBD) and the North Shore.", pricing: "10 bucks", location: "Sydney NSW, Australia", link: "330x210.gif", gen_package_id: 5, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "sydney_bridge", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Darling Harbour", description: "Darling Harbour is a harbour adjacent to the city centre of Sydney, New South Wales, Australia. It is also a large recreational and pedestrian precinct that is situated on western outskirts of the Sydney central business district.", pricing: "10 bucks", location: "Sydney NSW 2000, Australia", link: "330x210.gif", gen_package_id: 5, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "darling", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Port Jackson", description: "Port Jackson, also called Sydney Harbour, is the natural harbour of Sydney, New South Wales, Australia. The harbour is an inlet of the Tasman Sea (part of the South Pacific Ocean). It is the location of the Sydney Opera House and Sydney Harbour Bridge.", pricing: "10 bucks", location: "Australia", link: "330x210.gif", gen_package_id: 5, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "jackson", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "The Rocks", description: "The Rocks is an urban locality, tourist precinct and historic area of Sydney's city centre, in the state of New South Wales, Australia. It is located on the southern shore of Sydney Harbour, immediately north-west of the Sydney central business district.", pricing: "10 bucks", location: "NSW 2000, Australia", link: "330x210.gif", gen_package_id: 5, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "rocks", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Sydney Tower Eye", description: "Sydney Tower is Sydney's tallest structure, it is also the second tallest observation tower in the Southern Hemisphere.", pricing: "10 bucks", location: "100 Market St, Sydney NSW 2000, Australia", link: "330x210.gif", gen_package_id: 5, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "sydney_tower", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Pearl Harbor", description: "Pearl Harbor is a lagoon harbor on the island of Oahu, Hawaii, west of Honolulu. Much of the harbor and surrounding lands is a United States Navy deep-water naval base. It is also the headquarters of the United States Pacific Fleet. The attack on Pearl Harbor by the Empire of Japan on Sunday, December 7, 1941 brought the United States into World War II.", pricing: "10 bucks", location: "1 Arizona Memorial Place, Aiea, HI 96818", link: "330x210.gif", gen_package_id: 1, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "pearl", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "London Bridge", description: "\"London Bridge\" refers to several historical bridges that have spanned the River Thames between the City of London and Southwark, in central London. The current crossing, which opened to traffic in 1973, is a box girder bridge built from concrete and steel.", pricing: "N/A", location: "London, United Kingdom", link: "330x210.gif", gen_package_id: 2, image_description: nil, phone: nil, website: nil, hours: nil, rating: "4.4", iframe_id: "london_bridge", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Wild Life Sydney Zoo", description: "Wild Life Sydney Zoo (formerly Sydney Wildlife World) is a wildlife park in the heart of the city of Sydney, Australia. Officially opened in September 2006, it is located on the city side of the Darling Harbour leisure and retail precinct, next to Sydney Aquarium and Madame Tussauds Sydney.", pricing: "10 bucks", location: "1-5 Wheat Rd, Darling Harbour NSW 2000, Australia", link: "330x210.gif", gen_package_id: 5, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "sydney_zoo", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Iao Valley State Park", description: "Iao Valley  is a lush, stream-cut valley in West Maui, Hawaii, located 5 kilometres (3.1 mi) west of Wailuku. Because of its natural beauty and historical significance, it has become a popular tourist location. It was designated a National Natural Landmark in 1972.", pricing: "10 bucks", location: "Wailuku, HI 96793", link: "330x210.gif", gen_package_id: 1, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "iao", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "The White House", description: "The White House is the official residence and principal workplace of the President of the United States, located at 1600 Pennsylvania Avenue NW in Washington, D.C. It has been the residence of every U.S. president since John Adams in 1800.", pricing: "10 bucks", location: "1600 Pennsylvania Ave NW, Washington, D.C., DC 20500", link: "330x210.gif", gen_package_id: 6, image_description: nil, phone: "N/A", website: "http://www.whitehouse.gov/", hours: "N/A", rating: "4", iframe_id: "white_house", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "United States Capitol Building", description: "The United States Capitol, atop Capitol Hill at the eastern end of the National Mall in Washington, D.C., is the seat of the United States Congress, the legislative branch of the U.S. federal government, completed in the year 1800.", pricing: "10 bucks", location: "East Capitol St NE & First St SE, Washington, DC 20004", link: "330x210.gif", gen_package_id: 6, image_description: nil, phone: "N/A", website: "N/A", hours: "N/A", rating: "5", iframe_id: "us_capitol", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Lincoln Memorial", description: "The Lincoln Memorial is an American national monument built to honor the 16th President of the United States, Abraham Lincoln.", pricing: "10 bucks", location: "600 Independence Ave SW, Washington, DC 20560", link: "330x210.gif", gen_package_id: 6, image_description: nil, phone: "202.426.6841", website: "http://lincoln-memorial.org/", hours: "24/7", rating: "5", iframe_id: "smith_air_space", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "The British Museum", description: "The British Museum is a museum in London dedicated to human history and culture. Its permanent collection, numbering some 8 million works, is among the largest and most comprehensive in existence and originates from all continents, illustrating and documenting the story of human culture from its beginnings to the present.", pricing: "$12.42 - $21.49", location: "Great Russell St, London WC1B 3DG, United Kingdom", link: "330x210.gif", gen_package_id: 2, image_description: nil, phone: "+44 20 7323 8299", website: nil, hours: "12:00 am – 5:30 pm, 10:00 pm – 12:00 am", rating: "4.6", iframe_id: "british_museum", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Taronga Zoo", description: "Taronga Zoo is the city zoo of Sydney, New South Wales, Australia and is located on the shores of Sydney Harbour in the suburb of Mosman.", pricing: "Talk to Zack", location: "Bradleys Head Rd, Mosman NSW 2088, Australia", link: "330x210.gif", gen_package_id: 5, image_description: nil, phone: "+61 2 9969 2777", website: "http://taronga.org.au/taronga-zoo", hours: "9:30 am – 5:00 pm", rating: "4.5", iframe_id: "taronga", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Space Needle", description: "The Space Needle is an observation tower in Seattle, Washington, a landmark of the Pacific Northwest, and a symbol of Seattle. It was built in the Seattle Center for the 1962 World's Fair, which drew over 2.3 million visitors, when nearly 20,000 people a day used its elevators.", pricing: "$$$", location: "400 Broad St, Seattle, WA 98109", link: "330x210.gif", gen_package_id: 4, image_description: nil, phone: "+1 206 905 2100", website: "spaceneedle.com", hours: "10:00 AM -- 11:00 PM", rating: "4.2", iframe_id: "needle", button_id: nil, website_url: "http://www.spaceneedle.com/home/", iframe_url: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2689.289373635538!2d-122.34927700000004!3d47.620506!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5490151f4ed5b7f9%3A0xdb2ba8689ed0920d!2sSpace+Needle!5e0!3m2!1sen!2sus!4v1417050525679", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Pacific Science Center", description: "The Pacific Science Center is a science museum located in Seattle, Washington and designed by Minoru Yamasaki for 1962 World’s Fair in Seattle. Pacific Science Center is an independent, non-profit science museum based in Seattle, Washington.", pricing: "$$", location: "200 2nd Ave N, Seattle, WA 98109", link: "330x210.gif", gen_package_id: 4, image_description: nil, phone: "+1 206 443 2001", website: "pacificsciencecenter.org", hours: "10:00 AM -- 5:00 PM", rating: "3.9", iframe_id: "psc", button_id: nil, website_url: "http://www.pacificsciencecenter.org/", iframe_url: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2689.3396296202754!2d-122.35162!3d47.619529!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5490154594cbfd31%3A0xdd89aeb9ae3b049e!2sPacific+Science+Center!5e0!3m2!1sen!2sus!4v1417490145539", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Seattle Art Museum", description: "The Seattle Art Museum is an art museum located in Seattle, Washington, USA.", pricing: "$", location: "1300 1st Ave, Seattle, WA 98101", link: "330x210.gif", gen_package_id: 4, image_description: nil, phone: "+1 206 654 3100", website: "seattleartmuseum.org", hours: "10:00 AM -- 5:00 PM", rating: "4.2", iframe_id: "sam", button_id: nil, website_url: "http://www.seattleartmuseum.org/", iframe_url: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2689.9705663078544!2d-122.33814400000001!3d47.60726199999999!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x54906ab22579184b%3A0x7b64e8eea04a8dc4!2sSeattle+Art+Museum!5e0!3m2!1sen!2sus!4v1417489975168", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Pike Place Market", description: "Pike Place Market is a public market overlooking the Elliott Bay waterfront in Seattle, Washington, United States. The Market opened August 17, 1907, and is one of the oldest continuously operated public farmers' markets in the United States.", pricing: "$$$", location: "Seattle, WA", link: "330x210.gif", gen_package_id: 4, image_description: nil, phone: "+1 206 682 7453", website: "N/A", hours: "N/A", rating: "4.5", iframe_id: "pike", button_id: nil, website_url: "javascript:void(0)", iframe_url: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5379.688304505614!2d-122.34219295000005!3d47.60972!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x54906ab2c151d6cb%3A0x60441d5f633e9f1c!2sPike+Place+Market%2C+Seattle%2C+WA!5e0!3m2!1sen!2sus!4v1417490046175", image_file_name: "sydney2.jpg", image_content_type: "image/jpeg", image_file_size: 171652, image_updated_at: "2014-12-04 07:55:05", image_thumb_file_name: "sydney2.jpg", image_thumb_content_type: "image/jpeg", image_thumb_file_size: 171652, image_thumb_updated_at: "2014-12-04 07:54:50", short_url: nil},
  {name: "Smithsonian Institution", description: "The Smithsonian Institution, established in 1846 \"for the increase and diffusion of knowledge,\" is a group of museums and research centers administered by the United States government.", pricing: "10 bucks", location: "1000 Jefferson Dr SW, Washington, DC 20004", link: "330x210.gif", gen_package_id: 6, image_description: nil, phone: "202-633-1000", website: "http://www.si.edu/", hours: "Mon - Sun\t8:30 AM to 5:30 PM", rating: "4.5", iframe_id: "smithsonian", button_id: nil, website_url: nil, iframe_url: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Statue of Liberty", description: "The Statue of Liberty is a colossal neoclassical sculpture on Liberty Island in the middle of New York Harbor, in Manhattan, New York City.", pricing: "10 bucks", location: "Liberty Island, New York, NY", link: "330x210.gif", gen_package_id: 3, image_description: nil, phone: "N/A", website: "http://www.statueoflibertytickets.com/?gclid=CjwKEAiA-5-kBRDylPG5096R8mASJABqEdm4WksXeSizuZpNOemlhyM56gWTz7Txn059zRwpFZWLThoCG1jw_wcB", hours: "Monday-Sunday\t8:30 am – 4:00 pm", rating: "5", iframe_id: "liberty", button_id: nil, website_url: nil, iframe_url: "https://www.google.com/maps/place/Statue+of+Liberty+National+Monument/@40.689249,-74.0445,17z/data=!3m1!4b1!4m2!3m1!1s0x0:0x40c6a5770d25022b", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "CenturyLink Field", description: "Seattles football stadium for the local pro team the Seattle Seahawks.", pricing: "$", location: "800 Occidental Ave S, Seattle, WA 98134", link: "330x210.gif", gen_package_id: 4, image_description: nil, phone: "+1 206 381 7555", website: "centurylinkfield.com", hours: "8:30 AM -- 5:00 PM", rating: "4.5", iframe_id: "century", button_id: nil, website_url: "http://www.centurylinkfield.com/", iframe_url: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2690.5933069637476!2d-122.33163900000001!3d47.595152!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x54906aa3b9f1182b%3A0xa636cd513bba22dc!2sCenturyLink+Field!5e0!3m2!1sen!2sus!4v1417490201205", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: "hawaii2.jpg", image_thumb_content_type: "image/jpeg", image_thumb_file_size: 210024, image_thumb_updated_at: "2014-12-13 08:13:35", short_url: nil}
])
GenHotel.create!([
  {name: "Warwick Seattle Hotel", description: "Upscale, contemporary quarters with floor-to-ceiling windows, plus an indoor pool & a smart eatery.", pricing: "$$", address: "401 Lenora St, Seattle, WA 98121", link: "www.hello.com", gen_package_id: 4, image_description: nil, website_url: nil, iframe_url: nil, phone: "(206) 443-4300", website: "http://warwickhotels.com/seattle/", hours: "24/7", rating: "3.5", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "New York Hilton", description: "It’s all about location in NYC and New York Hilton Midtown places you right in the heart of the action, within walking distance of a range of famous attractions, including Times Square, Central Park, Radio City Music Hall, and Broadway St.", pricing: "$$", address: "1335 Avenue of the Americas New York, NY", link: "www.hello.com", gen_package_id: 3, image_description: nil, website_url: nil, iframe_url: nil, phone: "(212) 586-7000", website: "http://www3.hilton.com/en/hotels/new-york/new-york-hilton-midtown-NYCNHHH/index.html?WT.mc_id=zMKWASR0AA1HN2OLS3GooglePlusBusiness4GPBPT5NYCNHHH", hours: "24/7", rating: "3.5", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "The Saint Regis New York", description: "Featuring dramatically renovated and redesigned guestrooms, suites, and public spaces along with the debut of the new King Cole Bar & Salon under renowned New York chef and restaurateur, John DeLucie, The St. Regis New York has unveiled a bold new era of glamour at Manhattan’s best address", pricing: "$$$", address: "New York, NY 10022", link: "www.hello.com", gen_package_id: 3, image_description: nil, website_url: nil, iframe_url: nil, phone: "(212) 753-4500", website: "http://www.tripadvisor.com/Hotel_Review-g60763-d93614-Reviews-The_St_Regis_New_York-New_York_City_New_York.html", hours: "24/7", rating: "4.5", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "The Fairmont Olympic Hotel", description: "Italian Renaissance-style landmark boasting a grand lobby & elegant rooms, plus a spa & fine dining.", pricing: "$$$", address: "411 University Street, Seattle, WA 98101", link: nil, gen_package_id: 4, image_description: nil, website_url: nil, iframe_url: nil, phone: "(206) 621-1700", website: "http://www.fairmont.com/seattle/?cmpid=google_sea_search-branded-us_branded-e-revsh&gclid=CjwKEAiA-5-kBRDylPG5096R8mASJABqEdm4JrCtsmZsT0yVQhji0OtCDybKaxiZ_ydrmYr2fx5QahoCp3_w_wcB", hours: "24/7", rating: "4.5", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "The Fairmont Orchid", description: "Discover a luxurious Hawaii resort on the Kohala Coast inspired by Culture, Well-Being and Genuine Aloha.  From Mauna Kea's winter snow-capped mountaintop to the flowing lava of Kilauea Volcano to tropical rainforests and a teeming undersea world, the Big Island of Hawaii has much to offer the spirited traveler.", pricing: "$240/ night", address: "1 N Kaniku Dr, Kohala Coast, HI 96743", link: "www.hello.com", gen_package_id: 1, image_description: nil, website_url: nil, iframe_url: nil, phone: "(808) 885-2000", website: "http://www.fairmont.com/orchid-hawaii/", hours: "24/7", rating: "4.6", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Hilton Hawaiian Village Waikiki Beach Resort", description: "The Hilton Hawaiian Village Waikiki Beach Resort is situated on 22 oceanfront acres of Waikiki's widest stretch of beach, amid lush tropical gardens and fragrant flowers.", pricing: "$300/ night", address: "2005 Kalia Rd, Honolulu, HI 96815", link: "www.hello.com", gen_package_id: 1, image_description: nil, website_url: nil, iframe_url: nil, phone: "(808) 949-4321", website: "http://www.hiltonhawaiianvillage.com/", hours: "24/7", rating: "3.9", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Mauna Kea Beach Hotel", description: "Stylish rooms with luxe amenities & private lanai plus myriad activities & clam bake in 1960s venue.", pricing: "$390 - $400/night", address: "62 Mauna Kea Beach Dr, Waimea, HI 96743", link: "www.hello.com", gen_package_id: 1, image_description: nil, website_url: nil, iframe_url: nil, phone: "(808) 882-7222", website: "http://www.princeresortshawaii.com/", hours: "24/7", rating: "4.5", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "The Ritz London", description: "Louis XVI rooms in belle epoque hotel, synonymous with luxury, serving a legendary afternoon tea.", pricing: "$540- $543 / night", address: "150 Piccadilly, London W1J 9BR, United Kingdom", link: "www.hello.com", gen_package_id: 2, image_description: nil, website_url: nil, iframe_url: nil, phone: "+44 20 7493 8181", website: "http://www.theritzlondon.com/", hours: "24/7", rating: "4.2", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Millennium Hotel London Mayfair", description: "Elegant en suite rooms in an 18th-century building with Italian and Japanese restaurants and a gym.", pricing: "$249-$261 /night", address: "44 Grosvenor Square, London W1K 2HP, United Kingdom", link: "www.hello.com", gen_package_id: 2, image_description: nil, website_url: nil, iframe_url: nil, phone: "+44 20 7629 9400", website: "http://www.millenniumhotels.co.uk/millenniummayfair/", hours: "24/7", rating: "4.0", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "The Bloomsbury Hotel", description: "Contemporary refit of a Lutyens-designed neo-Georgian hotel with elegant rooms, ballroom and chapel.", pricing: "$223/night", address: "16-22 Great Russell St, London WC1B 3NN, United Kingdom", link: "www.hello.com", gen_package_id: 2, image_description: nil, website_url: nil, iframe_url: nil, phone: "+44 20 7347 1000", website: "http://www.doylecollection.com/hotels/the-bloomsbury-hotel", hours: "24/7", rating: "4.1", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Central Station Hotel", description: "Central Station Hotel we’re all about providing a central, comfortable, affordable place to stay. Our friendly team works hard to ensure you have a great experience with us from the moment you book to when you check out.", pricing: "$140- $315 / night", address: "75 Wentworth Ave, Sydney NSW 2000, Australia", link: "www.hello.com", gen_package_id: 5, image_description: nil, website_url: nil, iframe_url: nil, phone: "+61 2 9212 1005", website: "http://www.centralstationhotel.com.au/", hours: "24/7", rating: "4.0", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Y Hotel Hyde Park", description: "If you’re looking for an affordable base from which to explore Sydney, then Y Hotel City South is the perfect choice. With spacious rooms and warm contemporary interiors, Y Hotel Hyde Park is right where you want to be and situated right in the heart of Sydney’s action.", pricing: "$75 - $81 / night", address: "5-11 Wentworth Ave, Sydney NSW 2000, Australia", link: "www.hello.com", gen_package_id: 5, image_description: nil, website_url: nil, iframe_url: nil, phone: "+61 2 9264 2451", website: "http://yhotels.com.au/", hours: "24/7", rating: "3.2", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Four Seasons Hotel Sydney", description: "Stunningly situated overlooking Sydney Harbour, Four Seasons Hotel Sydney puts you near the city’s vibrant shopping and business centres. Take in dramatic harbour views, discover Sydney's best restaurants, and explore the famous Rocks district, all near our five-star luxury hotel in Sydney's CBD.", pricing: "$330 - $710/ night", address: "199 George St, Sydney NSW 2000, Australia", link: "www.hello.com", gen_package_id: 5, image_description: nil, website_url: nil, iframe_url: nil, phone: "+61 2 9250 3100", website: "http://www.fourseasons.com/sydney/", hours: "24/7", rating: "4.2", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "The Willard Continental", description: "Elegant lodging for power players since 1850 features an ornate lobby, a classic cocktail bar & spa.", pricing: "$$$", address: "1401 Pennsylvania Ave Nw, Washington, DC 20004", link: "www.hello.com", gen_package_id: 6, image_description: nil, website_url: nil, iframe_url: nil, phone: "(202) 628-9100", website: "http://washington.intercontinental.com/specials-packages?src=ppc_google_brand_newyearpackage&gclid=CjwKEAiAnqWkBRCGm5uyu5r13jsSJACBZ4WyibaNeKamCnPN6a4bNJxhBF2Xq3WICTNb_wkauIFZNRoCxI_w_wcB", hours: "24/7", rating: "4", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Washington Court Hotel", description: "A sophisticated, independent Capitol Hill hotel located in downtown Washington DC, the Washington Court Hotel offers the ultimate in modern design and hospitality. Boasting a central location near Union Station and Capitol Hill, the Washington Court Hotel is a 265 room distinguished downtown DC hotel destination for both business, leisure travelers and DC’s elite.", pricing: "$", address: "525 New Jersey Avenue Northwest, Washington, DC 20001", link: "www.hello.com", gen_package_id: 6, image_description: nil, website_url: nil, iframe_url: nil, phone: "(202) 628-2100", website: "http://washingtoncourthotel.com/", hours: "24/7", rating: "3.5", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Capital Hill Hotel", description: "Discover the tranquil beauty of the Capitol Hill Historic District in one of the most centrally located hotels in Washington D.C. Elegant and intimate, Capitol Hill Hotel is a home away from home in the heart of the nation’s capitol, tucked away amidst the charming brick rowhouses of a residential neighborhood yet just a short walk away from Washington’s most important sites, including the Capitol Building, Supreme Court, Library of Congress, and the National Mall.", pricing: "$$", address: "200 C St Se, Washington, DC 20003", link: "www.hello.com", gen_package_id: 6, image_description: nil, website_url: nil, iframe_url: nil, phone: "(202) 543-6000", website: "http://capitolhillhotel-dc.com/", hours: "24/7", rating: "3.5", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Hotel Pennsylvania", description: "Great Manhattan sightseeing within walking distance. New York City's major transit hub across the street. Great shopping at your doorstep. Broadway shows, unforgettable activities, exciting night-life, and more restaurants than you can count.", pricing: "$", address: "401 7th Ave, New York", link: "www.hello.com", gen_package_id: 3, image_description: nil, website_url: nil, iframe_url: nil, phone: "212-736-5000", website: "http://www.hotelpenn.com/", hours: "24/7", rating: "3", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: "aaa"},
  {name: "Hotel Seattle", description: "Standard wallpapered units with TVs & minifridges, walking distance to major points of interest.", pricing: "$", address: "315 Seneca Street, Seattle, WA 98101", link: "www.hello.com", gen_package_id: 4, image_description: nil, website_url: nil, iframe_url: "", phone: "(206) 623-5111", website: "http://www.thehotelseattle.com/", hours: "24/7", rating: "2.5", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: "asdf"}
])
GenHotelImage.create!([
  {name: "Test", description: "This is a test.", link: "www.hello.com", gen_hotel_id: 1},
  {name: "Test", description: "This is a test.", link: "www.hello.com", gen_hotel_id: 2},
  {name: "Test", description: "This is a test.", link: "www.hello.com", gen_hotel_id: 2},
  {name: "Test", description: "This is a test.", link: "www.hello.com", gen_hotel_id: 3},
  {name: "Test", description: "This is a test.", link: "www.hello.com", gen_hotel_id: 4}
])
GenImage.create!([
  {link: "720x700.gif", name: "Test", description: "This is a test.", gen_package_id: 1},
  {link: "720x700.gif", name: "Test", description: "This is a test.", gen_package_id: 2},
  {link: "720x700.gif", name: "Test", description: "This is a test.", gen_package_id: 2},
  {link: "720x700.gif", name: "Test", description: "This is a test.", gen_package_id: 3},
  {link: "720x700.gif", name: "Test", description: "This is a test.", gen_package_id: 4}
])
GenPackage.create!([
  {name: "Hawaii", code: "23417489", description: nil, image_name: "Hawaii", image_link: "hawaii2.jpg", image_description: "This is Hawaii."},
  {name: "New York", code: "2459115", description: nil, image_name: "New York", image_link: "NewYork2.jpg", image_description: "This is New York."},
  {name: "Sydney", code: "1105779", description: nil, image_name: "Test", image_link: "sydney2.jpg", image_description: "This is not Seattle."},
  {name: "Washington", code: "2514815", description: nil, image_name: "Test", image_link: "washington2.jpg", image_description: "This is Washington"},
  {name: "Seattle", code: "2490383", description: nil, image_name: "Seattle", image_link: "seattle2.jpg", image_description: "This is a Seattle."},
  {name: "London", code: "44418", description: nil, image_name: "Test", image_link: "london2.jpg", image_description: "This is London"}
])
GenRestaurant.create!([
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 1, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 1, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 1, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 1, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Fish at the Rocks", description: "This is a test.", pricing: "$25.00 - $35.00", address: "29 Kent St Sydney NSW 2000 Australia", link: "www.hello.com", gen_package_id: 5, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: "http://www.fishattherocks.com.au/#", hours: nil, rating: "4.4", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "The Square", description: "Seasonal Modern French haute cuisine in a sophisticated yet quietly casual, art-filled dining room.", pricing: "$120.00-$140.00", address: "6-10 Bruton St London W1J 6PU United Kingdom", link: "330x210.gif", gen_package_id: 2, image_description: nil, website_url: "javascript:void(0)", iframe_url: nil, phone: "+44 20 7495 7100", website: "squarerestaurant.com", hours: "TALK TO ZACK", rating: "4.5", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Porters English Restaurant", description: "English restaurant for traditional recipes and Sunday roasts, with children's and pre-theatre menus", pricing: nil, address: "17 Henrietta St London WC2E 8QH, United Kingdom", link: nil, gen_package_id: 2, image_description: nil, website_url: nil, iframe_url: nil, phone: "+44 20 7836 6466", website: "porters-restaurant.com", hours: "12:00 pm - 11:00pm", rating: "3.7", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "ABC Kitchen", description: "Chic New American eatery via Jean-Georges Vongerichten sourcing local, organic ingredients.", pricing: "$$", address: "35 East 18th Street, New York, NY 10003", link: "www.hello.com", gen_package_id: 3, image_description: nil, website_url: nil, iframe_url: nil, phone: "(212) 475-5829", website: "http://www.abchome.com/eat/abc-kitchen/", hours: "Monday-Sunday 12:00 – 3:00 pm, 5:30 – 10:30 pm", rating: "4.5", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Kandoo Restaurant", description: "Iranian dishes prepared in a simple restaurant with two dining rooms and a small courtyard garden.", pricing: "$5.00 - $38.00", address: "458 Edgware Rd London W2 1EJ United Kingdom", link: "www.hello.com", gen_package_id: 2, image_description: nil, website_url: nil, iframe_url: nil, phone: "020 7724 6769", website: "kandoorestaurant.co.uk", hours: nil, rating: "4.2", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Daniel", description: "Daniel Boulud's elegant French flagship where jackets are required & expense accounts come in handy.", pricing: "$$$", address: "60 East 65th Street, New York, NY 10065", link: "www.hello.com", gen_package_id: 3, image_description: nil, website_url: nil, iframe_url: nil, phone: "(212) 288-0033", website: "http://danielnyc.com/", hours: "Monday-Saturday 5:30 – 11:00 pm", rating: "5", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Per Se", description: "Chef Thomas Keller's New American restaurant offers luxe fixed-price menus with Central Park views.", pricing: "$$$", address: "10 Columbus Circle #4, New York, NY 10019", link: "www.hello.com", gen_package_id: 3, image_description: nil, website_url: nil, iframe_url: nil, phone: "(212) 823-9335", website: "http://www.thomaskeller.com/per-se", hours: "Friday-Sunday 11:30 am – 1:30 pm, 5:30 – 10:00 pm", rating: "4.5", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Zafferano", description: "Sophisticated Italian cuisine served in an exposed brick dining room with striped banquettes", pricing: nil, address: "15 Lowndes St London SW1X 9EY United Kingdom", link: nil, gen_package_id: 2, image_description: nil, website_url: nil, iframe_url: nil, phone: "020 7724 6769", website: "zafferanorestaurant.com", hours: nil, rating: "4.2", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Pizza Express- Southhampton Row", description: "Chain pizzeria where chefs in striped t-shirts toss handmade pizzas. Great place to grab a bit with friends.", pricing: "$15.00 - $20.00", address: "114-117 Southampton Row London WC1B 5AA United Kingdom", link: "www.hello.com", gen_package_id: 2, image_description: nil, website_url: nil, iframe_url: nil, phone: "+44 20 7430 1011", website: "pizzaexpress.com", hours: nil, rating: "4.0", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Quay", description: "This is a test.", pricing: "$175.00", address: "Upper Level, Overseas Passenger Terminal 5 Hickson Road The Rocks NSW 2000 Australia", link: "www.hello.com", gen_package_id: 5, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: "quay.com.au", hours: nil, rating: nil, iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Flying Fish Restaurant & Bar", description: "This is a test.", pricing: "$30.00 - $40.00", address: "Pier 21, Jones Bay Wharf, Pyrmont NSW 2009 Australia", link: "www.hello.com", gen_package_id: 5, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: "flyingfish.com.au", hours: nil, rating: nil, iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "The Apollo Restaurant", description: "", pricing: "$10.00 - $40.00", address: "44 Macleay St Potts Point NSW 2010 Australia", link: "www.hello.com", gen_package_id: 5, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: "http://www.theapollo.com.au/", hours: nil, rating: nil, iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "CHISWICK", description: "", pricing: "$15.00 - $55.00", address: "65 Ocean St Woollahra NSW 2025 Australia", link: "www.hello.com", gen_package_id: 5, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: "http://www.chiswickrestaurant.com.au/", hours: nil, rating: nil, iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "komi", description: "KOMI serves a set multi-course tasting dinner for $135 per person, beginning with a series of mezzethakia – small, light dishes – and progressing to pasta, a family-style entrée and desserts. There are no printed menus.\nWe offer an optional wine pairing for $70.", pricing: "$$$", address: "1509 17th St Nw, Washington, DC 20036", link: "www.hello.com", gen_package_id: 6, image_description: nil, website_url: nil, iframe_url: nil, phone: "(202) 332-9200", website: "http://www.komirestaurant.com/", hours: "Tue - Sat\t5:30 PM to 9:30 PM", rating: "4.5", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Bens Chili Bowl", description: "On August 22, 1958, Ben’s Chili Bowl opened for business.\n\nFrom the tumult of the late 60’s race riots to the tough times in the 70’s and 80’s and finally to the revitalization of the U Street Corridor beginning in the 90’s, Ben’s has seen it all.  Bill Cosby and thousands of others attended our 45th anniversary in August 2003.", pricing: "$", address: "1213 U St Nw, Washington, DC 20009", link: "www.hello.com", gen_package_id: 6, image_description: nil, website_url: nil, iframe_url: nil, phone: "(202) 667-0909", website: "http://benschilibowl.com/", hours: "Breakfast 6am - 10:45am Main Menu 10:45am - 2am", rating: "3.5", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "metropolitan Grill", description: "Classic upscale steakhouse decorated in wood, brass & velvet with a 60-ft. marble bar.", pricing: "$$$", address: "820 2nd Avenue, Seattle, WA 98104", link: "www.hello.com", gen_package_id: 4, image_description: nil, website_url: nil, iframe_url: "https://www.google.com/maps/embed/v1/place?q=Metropolitan%20Grill%2C%202nd%20Avenue%2C%20Seattle%2C%20WA%2C%20United%20States&key=AIzaSyCut1cnBQYw80bK0y8C2MLfOX2albDaQUM", phone: "(206) 624-3287", website: "http://www.themetropolitangrill.com/", hours: "Monday-Sunday\t11:00AM – 10:00 PM", rating: "4", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Black Salt", description: "Fancy american seafood restaurant which offers many special events.", pricing: "$$$", address: "4883 MacArthur Blvd., Washington D.C. 20007", link: "www.hello.com", gen_package_id: 6, image_description: nil, website_url: nil, iframe_url: nil, phone: "(202) 342-9101", website: "http://blacksaltrestaurant.com/", hours: "Mon - Thu\t11:30 AM to 2:30 PM", rating: "4", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "Rays Boathouse", description: "Long-standing dockside restaurant & cafe serving Pacific NW seafood with views of Shilshole Bay.", pricing: "$$$", address: "6049 Seaview Avenue Northwest, Seattle, WA 98107", link: nil, gen_package_id: 4, image_description: nil, website_url: nil, iframe_url: nil, phone: "(206) 789-3770", website: "http://www.rays.com/", hours: "Monday-Sunday 5:00PM - 9:30PM", rating: "4", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: nil},
  {name: "canlis", description: "A fine dining restaurant, where fancy dress and a sport coat are required.", pricing: "$$$", address: "2576 Aurora Ave N, Seattle, WA 98109", link: "www.hello.com", gen_package_id: 4, image_description: nil, website_url: nil, iframe_url: "https://www.google.com/maps/embed/v1/place?q=Canlis%20Restaurant%2C%20Seattle%2C%20WA%2C%20United%20States&key=AIzaSyCut1cnBQYw80bK0y8C2MLfOX2albDaQUM", phone: "(206) 283-3313", website: "http://canlis.com/", hours: "Monday-Sunday 5:30AM - 9:30PM", rating: "4", iframe_id: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, image_thumb_file_name: nil, image_thumb_content_type: nil, image_thumb_file_size: nil, image_thumb_updated_at: nil, short_url: "asdf"}
])
GenRestaurantImage.create!([
  {name: "Test", description: "This is a test.", link: "www.hello.com", gen_restaurant_id: 1},
  {name: "Test", description: "This is a test.", link: "www.hello.com", gen_restaurant_id: 2},
  {name: "Test", description: "This is a test.", link: "www.hello.com", gen_restaurant_id: 2},
  {name: "Test", description: "This is a test.", link: "www.hello.com", gen_restaurant_id: 3},
  {name: "Test", description: "This is a test.", link: "www.hello.com", gen_restaurant_id: 4}
])
HolPackage.create!([
  {name: "Christmas", link: "christmas"},
  {name: "Spring Break", link: "spring_break"},
  {name: "Thanksgiving", link: "thanksgiving"},
  {name: "Valentine's Day", link: "valentines"}
])
Question.create!([
  {text: "What kind of vacation are you looking for?"},
  {text: "Do you like the water/coast?"},
  {text: "Would you like to go outside the United States?"},
  {text: "Are you looking for a family freindly destination?"},
  {text: "What kind of weather do you like?"}
])
