User.create!([
  {email: "zackh1998@gmail.com", encrypted_password: "$2a$10$DVaAPyvnhcvxZCAJMbrmY.t1LKqtclnEFRwo5bTEn8tbGYti1ayZq", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2014-12-03 04:31:42", last_sign_in_at: "2014-12-03 04:31:42", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1"}
])
Answer.create!([
  {text: "Hot Weather", score: 100, color: "red", question_id: 1, label: "hot"},
  {text: "Temperate Weather", score: 50, color: "green", question_id: 1, label: "temperate"},
  {text: "Cold Weather", score: 0, color: "blue", question_id: 1, label: "cold"},
  {text: "Exciting", score: 100, color: "red", question_id: 2, label: "exciting"},
  {text: "Normal", score: 50, color: "green", question_id: 2, label: "normal"},
  {text: "Relaxing", score: 0, color: "blue", question_id: 2, label: "relaxing"},
  {text: "Yes", score: 100, color: "red", question_id: 3, label: "yes"},
  {text: "Unsure", score: 50, color: "green", question_id: 3, label: "no"},
  {text: "No", score: 0, color: "blue", question_id: 3, label: "unsure"},
  {text: "Yes", score: 100, color: "red", question_id: 4, label: "yes"},
  {text: "Unsure", score: 50, color: "green", question_id: 4, label: "no"},
  {text: "No", score: 0, color: "blue", question_id: 4, label: "unsure"},
  {text: "Yes", score: 100, color: "red", question_id: 5, label: "yes"},
  {text: "Unsure", score: 50, color: "green", question_id: 5, label: "no"},
  {text: "No", score: 0, color: "blue", question_id: 5, label: "unsure"}
])
AnswerValue.create!([
  {score: 100, gen_package_id: 1, question_id: 1},
  {score: 40, gen_package_id: 1, question_id: 2},
  {score: 100, gen_package_id: 1, question_id: 3},
  {score: 15, gen_package_id: 1, question_id: 4},
  {score: 80, gen_package_id: 1, question_id: 5},
  {score: 20, gen_package_id: 2, question_id: 1},
  {score: 40, gen_package_id: 2, question_id: 2},
  {score: 70, gen_package_id: 2, question_id: 3},
  {score: 90, gen_package_id: 2, question_id: 4},
  {score: 65, gen_package_id: 2, question_id: 5},
  {score: 30, gen_package_id: 3, question_id: 1},
  {score: 50, gen_package_id: 3, question_id: 2},
  {score: 60, gen_package_id: 3, question_id: 3},
  {score: 0, gen_package_id: 3, question_id: 4},
  {score: 60, gen_package_id: 3, question_id: 5},
  {score: 20, gen_package_id: 4, question_id: 1},
  {score: 80, gen_package_id: 4, question_id: 2},
  {score: 80, gen_package_id: 4, question_id: 3},
  {score: 0, gen_package_id: 4, question_id: 4},
  {score: 80, gen_package_id: 4, question_id: 5},
  {score: 95, gen_package_id: 5, question_id: 1},
  {score: 90, gen_package_id: 5, question_id: 2},
  {score: 88, gen_package_id: 5, question_id: 3},
  {score: 95, gen_package_id: 5, question_id: 4},
  {score: 75, gen_package_id: 5, question_id: 5},
  {score: 60, gen_package_id: 6, question_id: 1},
  {score: 40, gen_package_id: 6, question_id: 2},
  {score: 50, gen_package_id: 6, question_id: 3},
  {score: 0, gen_package_id: 6, question_id: 4},
  {score: 90, gen_package_id: 6, question_id: 5}
])
GenAttraction.create!([
  {name: "Pearl Harbor", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", pricing: "10 bucks", location: "1 Arizona Memorial Place, Aiea, HI 96818", link: "330x210.gif", gen_package_id: 1, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "pearl", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Hawaii Volcanoes National Park", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", pricing: "10 bucks", location: "Hawaii Volcanoes National Park, HI 96718", link: "330x210.gif", gen_package_id: 1, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "volcanoes", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Diamond Head State Monument", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", pricing: "10 bucks", location: "Honolulu, HI 96815", link: "330x210.gif", gen_package_id: 1, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "diamond", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Hanauma Bay", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", pricing: "10 bucks", location: "100 Hanauma Bay Rd, Honolulu, HI 96825", link: "330x210.gif", gen_package_id: 1, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "hanauma", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Iolani Palace", description: "This is a test.", pricing: "10 bucks", location: "364 S King St, Honolulu, HI 96813", link: "330x210.gif", gen_package_id: 1, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "iolani", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Sea Life Park Hawaii", description: "This is a test.", pricing: "10 bucks", location: "41-202 Kalanianaole Hwy, Waimanalo, HI 96795", link: "330x210.gif", gen_package_id: 1, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "sea_life", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Waipio Valley", description: "This is a test.", pricing: "10 bucks", location: "48-5416 Government Main Rd, Honokaa, HI 96727", link: "330x210.gif", gen_package_id: 1, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "waipio", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Maui Ocean Center", description: "This is a test.", pricing: "10 bucks", location: "192 Maalaea Rd, Wailuku, HI 96793", link: "330x210.gif", gen_package_id: 1, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "moc", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Iao Valley State Park", description: "This is a test.", pricing: "10 bucks", location: "Wailuku, HI 96793", link: "330x210.gif", gen_package_id: 1, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "iao", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Tower of London", description: "This is a test.", pricing: "10 bucks", location: "London EC3N 4AB, United Kingdom", link: "330x210.gif", gen_package_id: 2, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "london_tower", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "London Eye", description: "This is a test.", pricing: "10 bucks", location: "London SE1 7PB, United Kingdom", link: "330x210.gif", gen_package_id: 2, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "london_eye", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Buckingham Palace", description: "This is a test.", pricing: "10 bucks", location: "London SW1A 1AA, United Kingdom", link: "330x210.gif", gen_package_id: 2, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "buckingham", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Trafalgar Square", description: "This is a test.", pricing: "10 bucks", location: "Westminster, London WC2N 5DN, United Kingdom", link: "330x210.gif", gen_package_id: 2, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "trafalgar", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "The British Museum", description: "This is a test.", pricing: "10 bucks", location: "Great Russell St, London WC1B 3DG, United Kingdom", link: "330x210.gif", gen_package_id: 2, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "british_museum", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "London Bridge", description: "This is a test.", pricing: "10 bucks", location: "London, United Kingdom", link: "330x210.gif", gen_package_id: 2, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "london_bridge", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Churchill War Rooms", description: "This is a test.", pricing: "10 bucks", location: "Clive Steps, King Charles Street, London SW1A 2AQ, United Kingdom", link: "330x210.gif", gen_package_id: 2, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "churchill", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "The National Gallery", description: "This is a test.", pricing: "10 bucks", location: "Trafalgar Square, London WC2N 5DN, United Kingdom", link: "330x210.gif", gen_package_id: 2, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "gallery", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Empire State Building", description: "This is a test.", pricing: "10 bucks", location: "350 5th Ave, New York, NY 10118", link: "330x210.gif", gen_package_id: 3, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "empire", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Statue of Liberty", description: "This is a test.", pricing: "10 bucks", location: "Liberty Island, New York, NY", link: "330x210.gif", gen_package_id: 3, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "liberty", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Times Square", description: "This is a test.", pricing: "10 bucks", location: "Manhattan, NY 10036", link: "330x210.gif", gen_package_id: 3, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "times_sq", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Madison Square Garden", description: "This is a test.", pricing: "10 bucks", location: "4 Pennsylvania Plaza, New York, NY 10001", link: "330x210.gif", gen_package_id: 3, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "madison_sq", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Central Park", description: "This is a test.", pricing: "10 bucks", location: "New York, NY", link: "330x210.gif", gen_package_id: 3, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "cen_pk", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Brooklyn Bridge", description: "This is a test.", pricing: "10 bucks", location: "New York, NY", link: "330x210.gif", gen_package_id: 3, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "bklyn_bridge", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Yankee Stadium", description: "This is a test.", pricing: "10 bucks", location: "1 E 161st St, Bronx, NY 10451", link: "330x210.gif", gen_package_id: 3, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "yankee", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Space Needle", description: "This is a test.", pricing: "$$$", location: "400 Broad St, Seattle, WA 98109", link: "330x210.gif", gen_package_id: 4, image_description: nil, phone: "+1 206 905 2100", website: "spaceneedle.com", hours: "10:00 AM -- 11:00 PM", rating: "4.2", iframe_id: "needle", button_id: nil, website_url: "http://www.spaceneedle.com/home/", iframe_url: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2689.289373635538!2d-122.34927700000004!3d47.620506!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5490151f4ed5b7f9%3A0xdb2ba8689ed0920d!2sSpace+Needle!5e0!3m2!1sen!2sus!4v1417050525679"},
  {name: "Experience Music Project", description: "This is a test.", pricing: "$$", location: "325 5th Ave N, Seattle, WA 98109", link: "330x210.gif", gen_package_id: 4, image_description: nil, phone: "+1 206 770 2700", website: "empmuseum.org", hours: "10:00 AM -- 5:00 PM", rating: "4.2", iframe_id: "emp", button_id: nil, website_url: "http://www.empmuseum.org/", iframe_url: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2689.2391683091296!2d-122.34812400000001!3d47.621482!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x54901546f87aca63%3A0xd1e929cd1149d812!2sEMP+Museum!5e0!3m2!1sen!2sus!4v1417489798101"},
  {name: "Seattle Art Museum", description: "This is a test.", pricing: "$", location: "1300 1st Ave, Seattle, WA 98101", link: "330x210.gif", gen_package_id: 4, image_description: nil, phone: "+1 206 654 3100", website: "seattleartmuseum.org", hours: "10:00 AM -- 5:00 PM", rating: "4.2", iframe_id: "sam", button_id: nil, website_url: "http://www.seattleartmuseum.org/", iframe_url: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2689.9705663078544!2d-122.33814400000001!3d47.60726199999999!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x54906ab22579184b%3A0x7b64e8eea04a8dc4!2sSeattle+Art+Museum!5e0!3m2!1sen!2sus!4v1417489975168"},
  {name: "Pike Place Market", description: "This is a test.", pricing: "$$$", location: "Seattle, WA", link: "330x210.gif", gen_package_id: 4, image_description: nil, phone: "+1 206 682 7453", website: "N/A", hours: "N/A", rating: "4.5", iframe_id: "pike", button_id: nil, website_url: "javascript:void(0)", iframe_url: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5379.688304505614!2d-122.34219295000005!3d47.60972!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x54906ab2c151d6cb%3A0x60441d5f633e9f1c!2sPike+Place+Market%2C+Seattle%2C+WA!5e0!3m2!1sen!2sus!4v1417490046175"},
  {name: "Pacific Science Center", description: "This is a test.", pricing: "$$", location: "200 2nd Ave N, Seattle, WA 98109", link: "330x210.gif", gen_package_id: 4, image_description: nil, phone: "+1 206 443 2001", website: "pacificsciencecenter.org", hours: "10:00 AM -- 5:00 PM", rating: "3.9", iframe_id: "psc", button_id: nil, website_url: "http://www.pacificsciencecenter.org/", iframe_url: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2689.3396296202754!2d-122.35162!3d47.619529!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5490154594cbfd31%3A0xdd89aeb9ae3b049e!2sPacific+Science+Center!5e0!3m2!1sen!2sus!4v1417490145539"},
  {name: "CenturyLink Field", description: "This is a test.", pricing: "$", location: "800 Occidental Ave S, Seattle, WA 98134", link: "330x210.gif", gen_package_id: 4, image_description: nil, phone: "+1 206 381 7555", website: "centurylinkfield.com", hours: "8:30 AM -- 5:00 PM", rating: "4.5", iframe_id: "century", button_id: nil, website_url: "http://www.centurylinkfield.com/", iframe_url: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2690.5933069637476!2d-122.33163900000001!3d47.595152!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x54906aa3b9f1182b%3A0xa636cd513bba22dc!2sCenturyLink+Field!5e0!3m2!1sen!2sus!4v1417490201205"},
  {name: "Sydney Opera House", description: "This is a test.", pricing: "10 bucks", location: "Bennelong Point, Sydney NSW 2000, Australia", link: "330x210.gif", gen_package_id: 5, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "opera", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Bondi Beach", description: "This is a test.", pricing: "10 bucks", location: "NSW 2026, Australia", link: "330x210.gif", gen_package_id: 5, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "bondi", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Taronga Zoo", description: "This is a test.", pricing: "10 bucks", location: "Bradleys Head Rd, Mosman NSW 2088, Australia", link: "330x210.gif", gen_package_id: 5, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "taronga", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Manly Sea Life Sanctuary", description: "This is a test.", pricing: "10 bucks", location: "W Esplanade, Manly NSW 2095, Australia", link: "330x210.gif", gen_package_id: 5, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "manly", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Sydney Harbour Bridge", description: "This is a test.", pricing: "10 bucks", location: "Sydney NSW, Australia", link: "330x210.gif", gen_package_id: 5, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "sydney_bridge", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Darling Harbour", description: "This is a test.", pricing: "10 bucks", location: "Sydney NSW 2000, Australia", link: "330x210.gif", gen_package_id: 5, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "darling", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Port Jackson", description: "This is a test.", pricing: "10 bucks", location: "Australia", link: "330x210.gif", gen_package_id: 5, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "jackson", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "The Rocks", description: "This is a test.", pricing: "10 bucks", location: "NSW 2000, Australia", link: "330x210.gif", gen_package_id: 5, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "rocks", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "WILD LIFE Sydney Zoo", description: "This is a test.", pricing: "10 bucks", location: "1-5 Wheat Rd, Darling Harbour NSW 2000, Australia", link: "330x210.gif", gen_package_id: 5, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "sydney_zoo", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Sydney Tower Eye", description: "This is a test.", pricing: "10 bucks", location: "100 Market St, Sydney NSW 2000, Australia", link: "330x210.gif", gen_package_id: 5, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "sydney_tower", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "National Mall", description: "This is a test.", pricing: "10 bucks", location: "Washington, DC", link: "330x210.gif", gen_package_id: 6, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "ntl_mall", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "United States Capitol Building", description: "This is a test.", pricing: "10 bucks", location: "East Capitol St NE & First St SE, Washington, DC 20004", link: "330x210.gif", gen_package_id: 6, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "us_capitol", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Smithsonian Institution", description: "This is a test.", pricing: "10 bucks", location: "1000 Jefferson Dr SW, Washington, DC 20004", link: "330x210.gif", gen_package_id: 6, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "smithsonian", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "The White House", description: "This is a test.", pricing: "10 bucks", location: "1600 Pennsylvania Ave NW, Washington, D.C., DC 20500", link: "330x210.gif", gen_package_id: 6, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "white_house", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Smithsonian National Air and Space Museum", description: "This is a test.", pricing: "10 bucks", location: "600 Independence Ave SW, Washington, DC 20560", link: "330x210.gif", gen_package_id: 6, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "smith_air_space", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "Lincoln Memorial", description: "This is a test.", pricing: "10 bucks", location: "2 Lincoln Memorial Cir NW, Washington, DC 20037", link: "330x210.gif", gen_package_id: 6, image_description: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: "lincoln", button_id: nil, website_url: nil, iframe_url: nil},
  {name: "", description: "", pricing: "", location: "", link: "", gen_package_id: nil, image_description: "", phone: "", website: "", hours: "", rating: "", iframe_id: "", button_id: "", website_url: nil, iframe_url: nil}
])
GenHotel.create!([
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 1, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 1, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 1, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 1, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 2, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 2, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 2, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 3, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 3, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 3, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 3, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 3, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 4, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 4, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 5, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 5, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 5, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 5, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 5, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 5, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 6, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 6, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 6, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 6, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil}
])
GenHotelImage.create!([
  {name: "Test", description: "This is a test.", link: "www.hello.com", gen_hotel_id: 1},
  {name: "Test", description: "This is a test.", link: "www.hello.com", gen_hotel_id: 2},
  {name: "Test", description: "This is a test.", link: "www.hello.com", gen_hotel_id: 2},
  {name: "Test", description: "This is a test.", link: "www.hello.com", gen_hotel_id: 3},
  {name: "Test", description: "This is a test.", link: "www.hello.com", gen_hotel_id: 4}
])
GenImage.create!([
  {link: "720x700.gif", name: "Test", description: "This is a test.", gen_package_id: 1},
  {link: "720x700.gif", name: "Test", description: "This is a test.", gen_package_id: 2},
  {link: "720x700.gif", name: "Test", description: "This is a test.", gen_package_id: 2},
  {link: "720x700.gif", name: "Test", description: "This is a test.", gen_package_id: 3},
  {link: "720x700.gif", name: "Test", description: "This is a test.", gen_package_id: 4}
])
GenPackage.create!([
  {name: "Hawaii", code: "23417489", description: nil, image_name: "Hawaii", image_link: "hawaii2.jpg", image_description: "This is Hawaii."},
  {name: "London", code: "44418", description: nil, image_name: "Test", image_link: "london2.jpg", image_description: "This is London"},
  {name: "New York", code: "2459115", description: nil, image_name: "New York", image_link: "NewYork2.jpg", image_description: "This is New York."},
  {name: "Seattle", code: "2490383", description: nil, image_name: "Seattle", image_link: "seattle2.jpg", image_description: "This is a Seattle."},
  {name: "Sydney", code: "1105779", description: nil, image_name: "Test", image_link: "sydney2.jpg", image_description: "This is not Seattle."},
  {name: "Washington", code: "2514815", description: nil, image_name: "Test", image_link: "washington2.jpg", image_description: "This is Washington"}
])
GenRestaurant.create!([
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 1, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 1, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 1, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 1, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "The Square", description: "Seasonal Modern French haute cuisine in a sophisticated yet quietly casual, art-filled dining room.", pricing: "$120.00-$140.00", address: "6-10 Bruton St London W1J 6PU United Kingdom", link: "330x210.gif", gen_package_id: 2, image_description: nil, website_url: "javascript:void(0)", iframe_url: nil, phone: nil, website: "squarerestaurant.com", hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 2, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 2, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 3, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 3, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 3, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 3, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 3, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 4, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 4, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 5, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 5, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 5, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 5, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 5, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 5, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 6, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 6, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 6, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil},
  {name: "Test", description: "This is a test.", pricing: "10 bucks", address: "3343", link: "www.hello.com", gen_package_id: 6, image_description: nil, website_url: nil, iframe_url: nil, phone: nil, website: nil, hours: nil, rating: nil, iframe_id: nil}
])
GenRestaurantImage.create!([
  {name: "Test", description: "This is a test.", link: "www.hello.com", gen_restaurant_id: 1},
  {name: "Test", description: "This is a test.", link: "www.hello.com", gen_restaurant_id: 2},
  {name: "Test", description: "This is a test.", link: "www.hello.com", gen_restaurant_id: 2},
  {name: "Test", description: "This is a test.", link: "www.hello.com", gen_restaurant_id: 3},
  {name: "Test", description: "This is a test.", link: "www.hello.com", gen_restaurant_id: 4}
])
HolPackage.create!([
  {name: "Christmas", link: "christmas"},
  {name: "Spring Break", link: "spring_break"},
  {name: "Thanksgiving", link: "thanksgiving"},
  {name: "Valentine's Day", link: "valentines"}
])
Question.create!([
  {text: "What kind of weather do you like?"},
  {text: "What kind of vacation are you looking for?"},
  {text: "Do you like the water/coast?"},
  {text: "Would you like to go outside the United States?"},
  {text: "Are you looking for a family freindly destination?"}
])
